title: Zeldon Git Blog v01
description: > # this means to ignore newlines until "baseurl:"
  A test site for Jekyll based blogging on Github.
permalink: ':title/'
baseurl: "/blog_v01" # the subpath of your site, e.g. /blog
url: "https://zeldon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zeldon Tay # add your name
author-img: bert_profile.jpg # add your photo
about-author: Because the stochasticity of learning in this century requires documenting, thus I add here a setup. (I like dev work and do data science stuff in me job). # add description
social-twitter: https://twitter.com/ZeldonTay # add your Twitter handle
social-facebook: https://www.facebook.com/yuzhong.tay # add your Facebook handle
social-github: zeldon # add your Github handle
social-linkedin: https://www.linkedin.com/in/zeldontayyuzhong/ # add your Linkedin handle
social-email: zeldontay@gmail.com # add your Email address

# Discus
discus-identifier: zeldon # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
